faforever:
  api:
    base-url: https://api.taforever.com
    client-id: 05209670-36c5-40ad-b581-e71b7b49bd1a
    client-secret: 370965a5-e7f2-4fe1-9225-e4517476b6a5
    access-token-uri: ${faforever.api.base-url}/oauth/token
    max-page-size: 10_000
    max-result-size: 1_000_000
  map-generator:
    repoAndOwnerName: FAForever/Neroxis-Map-Generator
    queryVersionsUrl: https://api.github.com/repos/${faforever.map-generator.repoAndOwnerName}/releases
    minSupportedVersion: 1.4.3
  vault:
    base-url: http://content.taforever.com
    replayDownloadUrlFormat: ${faforever.vault.base-url}/faf/vault/replay_vault/replay.php?id=%s
  environments:
    "[taforever.com]":
      base-url: https://api.taforever.com
      client-id: 05209670-36c5-40ad-b581-e71b7b49bd1a
      client-secret: 370965a5-e7f2-4fe1-9225-e4517476b6a5
      access-token-uri: https://api.taforever.com/oauth/token
      replay-download-url-format: https://replay.faforever.com/%s
    "[localhost:8010]":
      base-url: http://localhost:8010
      client-id: 05209670-36c5-40ad-b581-e71b7b49bd1a
      client-secret: 370965a5-e7f2-4fe1-9225-e4517476b6a5
      access-token-uri: http://localhost:8010/oauth/token
      replay-download-url-format: https://replay.test.faforever.com/%s

logging:
  level:
    com.faforever.moderatorclient: DEBUG
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
